name: docker-pipeline-raju
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register Number
        run: echo "Hello World - 22IT056"
        
      - name: Checkout 
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: docker build -t vvraju56/ml-22it056 .
        
      - name: Docker Images
        run: docker images

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: push docker Image to DockerHub
        run: docker push vvraju56/ml-22it056
