name: docker-pipeline-raju
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register Number
        run: echo "Hello World - 22IT056"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t vvraju56/ml-22it056 .

      - name: List Docker Images
        run: docker images

     
